### ISSUE TITLE
One YAML Change and One Addition

### ISSUE THREAD

**Issue by bleszinske** [squidpickles/solar_weather#1]
Thanks so much for doing this ESPHome YAML file. It works great and was huge jumpstart for me to get my V3.0 weather station up and running. There was one change that I had to make... In the deep sleep section under wakeup_pin, I had to indent the number: GPIO25 and inverted: true lines two spaces. 
deep_sleep:
  run_duration: 60s
  sleep_duration: 4min
  wakeup_pin:
    number: GPIO25
    inverted: true

The one addition I did was to add the pmsx003 air quality monitor to the build... 

-Bill

**Comment by squidpickles** [comment]
Thanks @bleszinske for the report. I'm glad it's been helpful. TBH the setup I'm using is also a bit different from this, but I hoped it could be helpful for others as a jumping-off point. Adding air quality monitors to the setup is a great idea; I may do that, too!
