### ISSUE TITLE
GPIO25 Pin is Used Twice for Different Functions

### ISSUE THREAD

**Issue by mdframe** [squidpickles/solar_weather#2]
I noticed that the Wakeup Pin and the Pulse Counter are both using GPIO25.  I do not believe we can utilize the same pin for two different functions.  What is the best method to correct this simultaneous use of the same pin?

INFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/weather-station-v32.yaml...
Failed config

**deep_sleep: [source /config/esphome/weather-station-v32.yaml:41]
  
  Pin 25 is used in multiple places.**
  run_duration: 40s
  sleep_duration: 4min
  wakeup_pin: 
    number: 25
    inverted: True
    mode: 
      input: True
      output: False
      open_drain: False
      pullup: False
      pulldown: False
    ignore_strapping_warning: False
    drive_strength: 20.0
**sensor.pulse_counter: [source /config/esphome/weather-station-v32.yaml:104]
  
  Pin 25 is used in multiple places.**
  platform: pulse_counter
  pin: 
    number: 25
    mode: 
      input: True
      output: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0

Thx

**Comment by squidpickles** [comment]
Looks like an update added some pin reuse validation that was breaking this in newer versions of ESPHome. I added config that explicitly allows reuse between the pulse counter and deep sleep wakeup.

[This forum post](https://community.home-assistant.io/t/waking-up-from-deep-sleep-with-rain-gauge/650792/12) does challenge the approach of deep sleep combined with pulse counting, so it's possible this config isn't all that helpful anyway.

Ultimately, I found it easier to get power to the site than to keep working on minimizing power usage with solar/battery, so I'm not using this in my own setup. Happy to get any updates if people find something that works well.
